#! /bin/bash

if [ -n "$SHANAL_HOME" ]; then
  cd "$SHANAL_HOME"
fi

tvla cendrillon.tvp cendrillon.tvs -dot ~cendrillon.dot
dot -Tps ~cendrillon.dot -o ~cendrillon.ps
ps2pdf ~cendrillon.ps cendrillon.pdf

rm *.dot
rm *.tvp.out.tvs
rm *.ps

OS=`uname`
if [[ "$OS" == 'Darwin' ]]; then
  open cendrillon.pdf
fi
